### ISSUE TITLE
VS Code inserting '.' when adding two spaces after a word

### ISSUE THREAD

**Issue by lucask42** [AdamMaras/vscode-overtype#9]
Environment:
VS Code 1.25.1
macOS 10.13.6
tested with my usual other plugins installed and also with them all disabled
tested with my usual user settings and workspace settings and also with them all cleared out
tested with Overtype mode on and off

Steps to reproduce:
Install and enable Overtype
open any file
go to the end of a word and press the spacebar twice
-or- type any word and then press the spacebar twice

Expected result:
Two spaces

Actual result:
One space, a period, and another space

screen capture:
https://drive.google.com/open?id=1_LTljRKBqjVlaOO3_hAy-h-Hz4sndFLz

![screen cap](https://user-images.githubusercontent.com/25360463/44167549-59a5d400-a083-11e8-9231-c44be947ed98.gif)

**Comment by lucask42** [comment]
OK so this is probably a mac only issue.  There is a setting to insert periods on double spaces in the system preferences => Keyboard => Text tab.

Odd that the OS wasn't inserting the periods in VS Code unless Overtype was enabled...

**Comment by erichall** [comment]
Thanks @lucask42!

I encountered this today (10.14.6), it was called "Add full stop with double-space".

**Comment by kevincantu** [comment]
Oh and that's where the macOS smart quotes setting is, too!

**Comment by schneems** [comment]
You can disable this on mac via terminal with:

```
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
```

Then it requires a restart.

**Comment by p-i-** [comment]
On Ventura it's a little harder to find. System Settings -> Keyboard -> Text Input -> Input Sources -> Edit. (New dialog appears). "Add full stop to double space" -> toggle OFF.

**Comment by archcorsair** [comment]
> On Ventura it's a little harder to find. System Settings -> Keyboard -> Text Input -> Input Sources -> Edit. (New dialog appears). "Add full stop to double space" -> toggle OFF.

Thanks this did it for me. After I upgraded to Ventura it seems that it was enabled by default.

**Comment by v-iashin** [comment]
Is there a way to isolate the setting for VSCode specifically without installing extensions? Seems like a nice feature to have for other OS apps.

**Comment by jaidhyani** [comment]
> On Ventura it's a little harder to find. System Settings -> Keyboard -> Text Input -> Input Sources -> Edit. (New dialog appears). "Add full stop to double space" -> toggle OFF.

"Get a Macbook" they said. "It just works" they said. "You won't have to spend so much time hunting down obscure settings to fix things" they said.

I assume in the next version you'll have to sneak past a tiger and answer three riddles from a wizard.

**Comment by ckanitz** [comment]
> You can disable this on mac via terminal with:
> 
> ```
> defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
> ```
> 
> Then it requires a restart.

you, sir, just made my day. Thanks!

**Comment by alanwsmith** [comment]
I was able to solve this with a System Setting instead of having to use the command line. Wouldn't be surprised is the GUI and the CLI were setting the same thing, but I got to it from System Settings -> Keyboard -> Input Sources -> Add period with double-space

<img width="718" height="953" alt="Image" src="https://github.com/user-attachments/assets/837ed7f1-773f-44f2-b3be-bb33ef062bf3" />

<img width="717" height="952" alt="Image" src="https://github.com/user-attachments/assets/884212d3-8b5e-48e7-a502-4c9e7da850c7" />

**Comment by rkennedy** [comment]
> Is there a way to isolate the setting for VSCode specifically without installing extensions? Seems like a nice feature to have for other OS apps.

The following command modifies the setting only for VS Code:

```
defaults write com.microsoft.VSCode NSAutomaticPeriodSubstitutionEnabled -bool false
```

The change takes effect immediately — no restart required. (The command works for Cursor, too, just use `com.todesktop.230313mzl4w4u92` as the bundle identifier instead of `com.microsoft.VSCode`.) Change `false` to `true` to re-enable the behavior.

Another setting you might wish to disable is `ApplePressAndHoldEnabled`, especially if you're using Vim mode and expect holding the `k` key to move the cursor up rather than prompt you to type `ķ`.

If you want the settings to apply globally instead of just for VS Code, then you can do so in the System Settings, as shown in an earlier post on this issue.
